/* Screen */
export const PROVISION_SCREEN = 'PROVISION_SCREEN'
export const PROVISION_SCREEN_REQUEST = 'PROVISION_SCREEN_REQUEST'
export const EDIT_SCREEN = 'EDIT_SCREEN'
export const REMOVE_SCREEN = 'REMOVE_SCREEN'

/* Walls */
export const CREATE_WALL = 'CREATE_WALL'
export const EDIT_WALL = 'EDIT_WALL'
export const REMOVE_WALL = 'REMOVE_WALL'

